# -*- coding: utf-8 -*-
"""Hackathon Forecast Big Data 2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ma-ORAhYMxmeDUDNNjOn9UM7hRFys6I9

# **Passo 1: Configuração do Ambiente e Carregamento dos Dados**
"""

import pandas as pd
import numpy as np

try:

    df_transacoes = pd.read_parquet('transacoes_2022.parquet')
    df_produtos = pd.read_parquet('cadastro_produtos.parquet')
    df_pdvs = pd.read_parquet('cadastro_pdvs.parquet')

    print("Arquivos carregados com sucesso em DataFrames!")

    print("\nDimensões dos dados:")
    print(f"Transações: {df_transacoes.shape}")
    print(f"Produtos: {df_produtos.shape}")
    print(f"PDVs: {df_pdvs.shape}")

    print("\nAmostra dos dados de transações:")
    display(df_transacoes.head())

except FileNotFoundError as e:
    print(f"\nERRO: Arquivo não encontrado.")
    print("Verifique no painel de arquivos à esquerda se os nomes estão exatamente corretos e no diretório raiz ('/content/').")
    print(f"Detalhe do erro: {e}")

"""# **Passo 2: Análise e Pré-processamento**

# **2.1. Unificar os DataFrames**
"""

print("Colunas em df_transacoes:", df_transacoes.columns.tolist())
print("Colunas em df_produtos:", df_produtos.columns.tolist())
print("Colunas em df_pdvs:", df_pdvs.columns.tolist())

df_full = pd.merge(df_transacoes, df_produtos, left_on='internal_product_id', right_on='produto', how='left')

df_full = pd.merge(df_full, df_pdvs, left_on='internal_store_id', right_on='pdv', how='left')

print("DataFrame unificado com sucesso.")
print("Colunas disponíveis:", df_full.columns.tolist())

df_full['Data'] = pd.to_datetime(df_full['transaction_date'])

print("\nColuna de data convertida.")

print("\nContagem de valores nulos por coluna:")
print(df_full.isnull().sum())

colunas_para_remover = ['internal_store_id', 'internal_product_id', 'distributor_id', 'reference_date', 'transaction_date']
df_full.drop(columns=colunas_para_remover, inplace=True, errors='ignore')

print("\nColunas desnecessárias removidas.")

df_semanal = df_full.groupby([
    pd.Grouper(key='Data', freq='W-Sun'),
    'pdv',
    'produto'
]).agg(

    quantidade=('quantity', 'sum'),
    faturamento=('gross_value', 'sum')
).reset_index()

df_semanal['ano'] = df_semanal['Data'].dt.year
df_semanal['mes'] = df_semanal['Data'].dt.month
df_semanal['semana_do_ano'] = df_semanal['Data'].dt.isocalendar().week

print("\nDados agregados por semana com sucesso!")
print("Dimensões do DataFrame semanal:", df_semanal.shape)
display(df_semanal.head())

"""# **Passo 3: Engenharia de Features (Feature Engineering)**

# **3.1. Features de Lag (Atraso)**
"""

df_semanal.sort_values(by=['pdv', 'produto', 'Data'], inplace=True)

lags = [1, 2, 3, 4]
for lag in lags:
    coluna_nome = f'lag_{lag}_semana'
    df_semanal[coluna_nome] = df_semanal.groupby(['pdv', 'produto'])['quantidade'].shift(lag)

print("Features de Lag criadas.")
display(df_semanal[['Data', 'pdv', 'produto', 'quantidade', 'lag_1_semana', 'lag_2_semana']].head(10))

"""# **3.2. Features de Janela Móvel (Rolling Window)**"""

df_semanal['media_movel_4_semanas'] = df_semanal.groupby(['pdv', 'produto'])['quantidade'].shift(1).rolling(window=4, min_periods=1).mean()

df_semanal['std_movel_4_semanas'] = df_semanal.groupby(['pdv', 'produto'])['quantidade'].shift(1).rolling(window=4, min_periods=1).std()

df_semanal['max_movel_4_semanas'] = df_semanal.groupby(['pdv', 'produto'])['quantidade'].shift(1).rolling(window=4, min_periods=1).max()
df_semanal['min_movel_4_semanas'] = df_semanal.groupby(['pdv', 'produto'])['quantidade'].shift(1).rolling(window=4, min_periods=1).min()

print("Features de Janela Móvel criadas.")
display(df_semanal[['Data', 'pdv', 'produto', 'quantidade', 'media_movel_4_semanas', 'std_movel_4_semanas']].head(10))

"""# **3.3. Features de Data e Sazonalidade**"""

df_semanal['dia_do_mes'] = df_semanal['Data'].dt.day
df_semanal['eh_fim_de_mes'] = (df_semanal['dia_do_mes'] > 25).astype(int)
df_semanal['eh_inicio_de_mes'] = (df_semanal['dia_do_mes'] < 7).astype(int)

print("Features de Data criadas.")
display(df_semanal[['Data', 'dia_do_mes', 'eh_fim_de_mes', 'eh_inicio_de_mes']].head())

"""# **3.4. Incorporar e Codificar Features Categóricas**"""

df_final = pd.merge(df_semanal, df_produtos, on='produto', how='left')

df_final = pd.merge(df_final, df_pdvs, on='pdv', how='left')

colunas_categoricas = ['categoria', 'subcategoria', 'marca', 'fabricante', 'premise', 'categoria_pdv']

for col in colunas_categoricas:
    if col in df_final.columns:
        df_final[col] = df_final[col].astype('category').cat.codes

print("Features Categóricas incorporadas e codificadas.")
display(df_final[colunas_categoricas].head())

"""# **3.5. Limpeza Final**"""

df_final.fillna(0, inplace=True)

print("Valores nulos tratados. DataFrame final pronto para modelagem.")
display(df_final.head())

"""# **4. Treinamento do Modelo**"""

df_final['pdv'] = df_final['pdv'].astype(int)
df_final['produto'] = df_final['produto'].astype(int)

print("Tipos de dados de 'pdv' e 'produto' após a conversão:")
print(df_final[['pdv', 'produto']].dtypes)

"""# **4.1. Definição das Features (X) e do Alvo (y)**"""

import lightgbm as lgb
from sklearn.model_selection import train_test_split

target = 'quantidade'

features = [col for col in df_final.columns if col not in [
    'Data',
    'quantidade',
    'faturamento',
    'descricao',
    'tipos',
    'label'
]]

X = df_final[features]
y = df_final[target]

print(f"Número de features usadas no modelo: {len(features)}")
print("Exemplo de features:", features[:5])

"""# **4.2 - Dividir os dados, Treinar o modelo e Avaliar o modelo**"""

import lightgbm as lgb
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_absolute_error

target = 'quantidade'
features = [col for col in df_final.columns if col not in [
    'Data', 'quantidade', 'faturamento', 'descricao', 'tipos', 'label'
]]

X = df_final[features]
y = df_final[target]

data_final = df_final['Data'].max()
data_inicio_validacao = data_final - pd.Timedelta(weeks=4)

df_treino = df_final[df_final['Data'] < data_inicio_validacao]
df_validacao = df_final[df_final['Data'] >= data_inicio_validacao]

X_train, y_train = df_treino[features], df_treino[target]
X_val, y_val = df_validacao[features], df_validacao[target]

print("\n--- Treinando o Modelo LightGBM ---")
params = {
    'objective': 'regression_l1', 'metric': 'mae', 'n_estimators': 2000,
    'learning_rate': 0.01, 'feature_fraction': 0.8, 'bagging_fraction': 0.8,
    'bagging_freq': 1, 'lambda_l1': 0.1, 'lambda_l2': 0.1, 'num_leaves': 31,
    'verbose': -1, 'n_jobs': -1, 'seed': 42, 'boosting_type': 'gbdt',
}
model = lgb.LGBMRegressor(**params)
model.fit(X_train, y_train,
          eval_set=[(X_val, y_val)],
          eval_metric='mae',
          callbacks=[lgb.early_stopping(100, verbose=True)])

print("\n--- Avaliando a Performance do Modelo ---")
previsoes_val = model.predict(X_val)
mae = mean_absolute_error(y_val, previsoes_val)

def wmape(y_true, y_pred):
    return np.sum(np.abs(y_true - y_pred)) / np.sum(np.abs(y_true))

wmape_score = wmape(y_val, previsoes_val)
print(f"\n--- Performance na Validação Local ---")
print(f"Erro Absoluto Médio (MAE): {mae:.4f}")
print(f"WMAPE: {wmape_score:.4f} (ou {wmape_score*100:.2f}%)")
print("--------------------------------------")

lgb.plot_importance(model, figsize=(10, 12), max_num_features=30, height=0.8, title="Importância das Features")
plt.tight_layout()
plt.show()

"""# **5 - Geração das Previsões e Arquivo de Submissão**"""

print("--- 5.1. Retreinando o modelo com todos os dados de 2022 ---")
num_rodadas_otimo = model.best_iteration_
params['n_estimators'] = num_rodadas_otimo
model_final = lgb.LGBMRegressor(**params)
model_final.fit(X, y)
print(f"Modelo final treinado com sucesso usando {num_rodadas_otimo} estimadores.")

print("\n--- 5.2. Preparando estruturas para a previsão otimizada ---")

data_final_2022 = df_final['Data'].max()

data_inicio_filtro = data_final_2022 - pd.Timedelta(days=18)

df_recente = df_final[df_final['Data'] >= data_inicio_filtro]
pares_pdv_produto = df_recente[['pdv', 'produto']].drop_duplicates()
print(f"Filtro de 18 dias resultou em {len(pares_pdv_produto)} combinações PDV/Produto ativas.")
print(f"ESTIMATIVA DE LINHAS NA SUBMISSÃO FINAL: {len(pares_pdv_produto) * 5}")

datas_predicao = pd.to_datetime(['2023-01-08', '2023-01-15', '2023-01-22', '2023-01-29', '2023-02-05'])

df_predicao_base = pd.DataFrame()
for i, data in enumerate(datas_predicao, 1):
    temp_df = pares_pdv_produto.copy()
    temp_df['Data'] = data
    temp_df['semana'] = i
    df_predicao_base = pd.concat([df_predicao_base, temp_df], ignore_index=True)

features_atuais = df_final.loc[df_final.groupby(['pdv', 'produto'])['Data'].idxmax()].copy()

print("\n--- 5.3. Gerando previsões de forma iterativa e otimizada ---")
lista_previsoes = []
for i, data_semana in enumerate(datas_predicao, 1):
    print(f"Prevendo a Semana {i}/5...")
    df_pred_semana = df_predicao_base[df_predicao_base['semana'] == i].copy()
    df_pred_semana = pd.merge(df_pred_semana, features_atuais[features], on=['pdv', 'produto'], how='left')
    df_pred_semana['ano'] = df_pred_semana['Data'].dt.year
    df_pred_semana['mes'] = df_pred_semana['Data'].dt.month
    df_pred_semana['semana_do_ano'] = df_pred_semana['Data'].dt.isocalendar().week
    df_pred_semana['dia_do_mes'] = df_pred_semana['Data'].dt.day
    df_pred_semana['eh_fim_de_mes'] = (df_pred_semana['dia_do_mes'] > 25).astype(int)
    df_pred_semana['eh_inicio_de_mes'] = (df_pred_semana['dia_do_mes'] < 7).astype(int)
    df_pred_semana.fillna(0, inplace=True)
    X_pred = df_pred_semana[features]
    previsao = model_final.predict(X_pred)
    previsao[previsao < 0] = 0
    df_pred_semana['quantidade'] = np.round(previsao).astype(int)
    df_pred_semana['semana'] = i
    lista_previsoes.append(df_pred_semana[['semana', 'pdv', 'produto', 'quantidade']])
    novas_features = features_atuais.copy().set_index(['pdv', 'produto'])
    previsao_map = df_pred_semana.set_index(['pdv', 'produto'])['quantidade']
    novas_features['lag_4_semana'] = novas_features['lag_3_semana']
    novas_features['lag_3_semana'] = novas_features['lag_2_semana']
    novas_features['lag_2_semana'] = novas_features['lag_1_semana']
    novas_features['lag_1_semana'] = previsao_map
    novas_features['media_movel_4_semanas'] = novas_features[['lag_1_semana', 'lag_2_semana', 'lag_3_semana', 'lag_4_semana']].mean(axis=1)
    features_atuais = novas_features.reset_index()

print("\n--- 5.4. Salvando o arquivo de submissão ---")
df_submissao = pd.concat(lista_previsoes, ignore_index=True)
print("Amostra do arquivo de submissão:")
display(df_submissao.head())
print(f"Total de linhas na submissão FINAL: {df_submissao.shape[0]}")
df_submissao.to_parquet('submissao.parquet', index=False)
print("\nArquivo 'submissao.parquet' criado com sucesso!")